package com.example.gallery.Database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.gallery.Database.photos;

import com.example.gallery.Database.photosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photosDaoConfig;

    private final photosDao photosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photosDaoConfig = daoConfigMap.get(photosDao.class).clone();
        photosDaoConfig.initIdentityScope(type);

        photosDao = new photosDao(photosDaoConfig, this);

        registerDao(photos.class, photosDao);
    }
    
    public void clear() {
        photosDaoConfig.clearIdentityScope();
    }

    public photosDao getPhotosDao() {
        return photosDao;
    }

}
