package com.example.gallery.Database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PHOTOS".
 */
@Entity
public class photos {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String date;
    private String album;
    private String uri;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public photos() {
    }

    public photos(Long id) {
        this.id = id;
    }

    @Generated
    public photos(Long id, String name, String date, String album, String uri) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.album = album;
        this.uri = uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
